Social Network Ads Dataset Decision Tree

In [2]:
print("Hello world")

Hello world


In [5]:
import pandas as pd

In [ ]:
# Age is in a differen scale than estimated salary. Thus we need to convert them into a standard scale.

In [6]:
df = pd.read_csv("/home/msis/ahegde/aml-lab/projects/data/Social_Network_Ads.csv")

In [7]:
df

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0
...,...,...,...,...,...
395,15691863,Female,46,41000,1
396,15706071,Male,51,23000,1
397,15654296,Female,50,20000,1
398,15755018,Male,36,33000,0


In [8]:
df.head()

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0


In [9]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [13]:
x = df.iloc[:, 2:4].values
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [15]:
y = df.iloc[:, -1].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [16]:
import numpy as np

In [50]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=45)

In [19]:
x_test.astype(int)

array([[    52,  90000],
       [    53,  72000],
       [    40,  72000],
       [    57,  33000],
       [    40,  61000],
       [    19,  21000],
       [    32,  86000],
       [    35,  72000],
       [    25,  87000],
       [    59,  29000],
       [    29,  75000],
       [    45,  79000],
       [    24,  32000],
       [    56,  60000],
       [    39,  42000],
       [    19,  76000],
       [    26,  72000],
       [    47,  20000],
       [    18,  52000],
       [    20,  23000],
       [    37,  79000],
       [    55, 125000],
       [    35,  55000],
       [    40,  75000],
       [    29,  61000],
       [    18,  68000],
       [    29, 148000],
       [    25,  90000],
       [    47,  23000],
       [    38,  61000],
       [    43, 112000],
       [    40,  57000],
       [    59,  42000],
       [    26, 118000],
       [    35,  75000],
       [    45,  22000],
       [    26,  80000],
       [    35,  97000],
       [    20,  36000],
       [    60,  42000],


In [25]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [30]:
x_train

array([[-1.64383039, -0.04716677],
       [-0.16067515,  1.66262849],
       [ 0.63034098, -0.90206439],
       [-1.24832233, -1.40321127],
       [-1.74270741,  0.12970861],
       [-0.35842918,  0.07075015],
       [ 0.1359559 , -0.31247982],
       [ 1.71798816, -0.90206439],
       [ 0.1359559 , -0.25352136],
       [-0.06179814,  0.01179169],
       [ 0.43258695,  0.60137626],
       [-1.84158443, -1.31477359],
       [ 0.92697203,  1.10252314],
       [ 0.1359559 ,  0.27710475],
       [-0.25955217, -0.37143828],
       [-1.24832233,  0.27710475],
       [ 2.0146192 , -0.93154362],
       [-0.75393725,  1.3678362 ],
       [ 0.23483291, -0.31247982],
       [-1.0505683 , -0.45987596],
       [ 0.43258695,  0.15918783],
       [-1.84158443, -1.49164896],
       [ 0.82809501, -1.10841899],
       [-0.16067515, -0.45987596],
       [-0.25955217,  0.63085549],
       [ 1.71798816,  1.7805454 ],
       [-0.65506023,  0.12970861],
       [ 0.23483291, -0.28300059],
       [ 1.02584904,

In [31]:
x_test

array([[ 1.42135711,  0.60137626],
       [ 1.52023412,  0.07075015],
       [ 0.23483291,  0.07075015],
       [ 1.91574219, -1.07893976],
       [ 0.23483291, -0.25352136],
       [-1.84158443, -1.4326905 ],
       [-0.55618322,  0.48345935],
       [-0.25955217,  0.07075015],
       [-1.24832233,  0.51293858],
       [ 2.11349622, -1.19685668],
       [-0.85281426,  0.15918783],
       [ 0.72921799,  0.27710475],
       [-1.34719935, -1.10841899],
       [ 1.81686517, -0.28300059],
       [ 0.1359559 , -0.81362671],
       [-1.84158443,  0.18866706],
       [-1.14944531,  0.07075015],
       [ 0.92697203, -1.46216973],
       [-1.94046144, -0.51883442],
       [-1.74270741, -1.37373205],
       [-0.06179814,  0.27710475],
       [ 1.71798816,  1.63314926],
       [-0.25955217, -0.43039674],
       [ 0.23483291,  0.15918783],
       [-0.85281426, -0.25352136],
       [-1.94046144, -0.04716677],
       [-0.85281426,  2.31117151],
       [-1.24832233,  0.60137626],
       [ 0.92697203,

In [57]:
from sklearn import tree
#clf = tree.DecisionTreeClassifier(criterion='entropy', random_state=0)
clf = tree.DecisionTreeClassifier(criterion='gini')

In [58]:
clf.fit(x_train, y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,None
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [59]:
y_pred = clf.predict(x_test)

In [60]:
from sklearn.metrics import confusion_matrix

In [61]:
confusion_matrix(y_test, y_pred)

array([[54,  8],
       [11, 27]])

In [44]:
y_pred1 = clf.predict(x_test)

In [49]:
(43+21)/(43+21+11+5)

0.8

In [63]:
confusion_matrix(y_test, y_pred)

array([[54,  8],
       [11, 27]])

In [51]:
from sklearn.metrics import accuracy_score

In [55]:
from sklearn.metrics import classification_report

In [56]:
print(classification_report(y_test, y_pred1))

ValueError: Found input variables with inconsistent numbers of samples: [100, 80]

In [76]:
new_ind = np.array([[29, 95000]])
new_ind_sc = sc_x.transform(new_ind)
pred = clf.predict(new_ind_sc)

In [77]:
pred

array([1])